### ISSUE TITLE
gif is rendered slower than expected on android in 8.8.0, same gif not supported in 8.8.1

### ISSUE THREAD

**Issue by DeyanDanailov** [dream-sports-labs/react-native-fast-image#133]
Hey, guys, I tried to use the library for rendering animated gifs.

On @d11/react-native-fast-image 8.8.0 ios is working great but android is rendering slower than expected.

After an update to 8.8.1 I understood that the gif is not moving so maybe you are working on that problem.

Please let us know if we should expect an update with proper gif rendering on android. 

Thanks in advance, 
Best wishes,
 
- React Native version: 0.72.7

**Comment by princektripathi** [comment]
> Hey, guys, I tried to use the library for rendering animated gifs.
> 
> On @d11/react-native-fast-image 8.8.0 ios is working great but android is rendering slower than expected.
> 
> After an update to 8.8.1 I understood that the gif is not moving so maybe you are working on that problem.
> 
> Please let us know if we should expect an update with proper gif rendering on android.
> 
> Thanks in advance, Best wishes,
> 
> * React Native version: 0.72.7

Hi @DeyanDanailov, could you please share a reproducer for this issue?

**Comment by princektripathi** [comment]
@DeyanDanailov, I looked into reported issues and here are the findings - 

- Gif's performance issue on `8.8.0` - I have validated it and it looks good. However would be happy to re-look if you can share the reproducer
- Gif is not loading on `8.8.1` - This issue is fixed and will be rolled out in `8.8.2` (issue - https://github.com/dream-sports-labs/react-native-fast-image/pull/140#issue-2717406337)
